### ISSUE TITLE
Error in function use_SAMseq()

### ISSUE THREAD

**Issue by Gautam8387** [dasroy/broadSeq#1]
When attempting to run the example for "Differential Expression" using the use_SAMseq() function as shown below:

`result_sam <- use_SAMseq(se = se, colData_id = "stage", control = "Bud", treatment = "Cap", rank = TRUE)`

I encountered the following error:

`Error in use_SAMseq(se = se, colData_id = "stage", control = "Bud", treatment = "Cap", : could not find function "use_SAMseq"`

It seems that the `use_SAMseq()` function is not recognized or available, resulting in this error.

Thank you for your assistance.

**Comment by vondoRishi** [comment]
Updated and it should be fixed now .
Please re-install with this command

>>     if (!require("BiocManager", quietly = TRUE))
>>          install.packages("BiocManager")

> #### The following initializes usage of Bioc devel
>>     BiocManager::install(version='devel')
>>     BiocManager::install("broadSeq")
